// Generated by scripts/generate_version.py.
// CI regenerates this file for each firmware build.
#ifndef INCLUDE_VERSION_H_
#define INCLUDE_VERSION_H_

#include <string_view>

namespace firmware::version {

inline constexpr std::string_view kFirmwareVersion = "0.1.0-dev+local";
inline constexpr std::string_view kReleaseVersion = "0.1.0";
inline constexpr std::string_view kBaseVersion = "0.1.0";
inline constexpr std::string_view kGitSha = "local";
inline constexpr std::string_view kBuildTimestamp = "local";
inline constexpr std::string_view kBuildDate = "local";
inline constexpr int kMajor = 0;
inline constexpr int kMinor = 1;
inline constexpr int kPatch = 0;
inline constexpr bool kIsRelease = false;

}  // namespace firmware::version

#endif  // INCLUDE_VERSION_H_
